
spring:
  application:
    name: Test-camel
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
camel:
  component:
    servlet:
      mapping:
        context-path: /javadevjournal/*
        match-on-uri-prefix: true
discount:
  newDiscount: 2000
  listDiscount: 6000
#server:
#  port: 8081
